### ISSUE TITLE
[SETTING] 스켈레톤 프로젝트 생성

### ISSUE THREAD

**Issue by yony-k** [yony-k/TALARIA-AUTH#1]
## 🍚 Description

- 스켈레톤 프로젝트 생성

## 🍚 To-do

- [ ] Spring boot Initializer 로 프로젝트 생성
- [ ] build.gradle 에 필요의존성 추가
- [ ] 패키지 분리 및 dummy.txt 추가

## 🍚 ETC

- 2024.09.04
